In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
dataset = pd.read_csv('insurance.csv')
dataset.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [3]:
dataset.isna().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [4]:
df = dataset.copy()

In [5]:
df.describe()

age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

In [6]:
df.describe(include='O')

sex smoker     region
count   1338   1338       1338
unique     2      2          4
top     male     no  southeast
freq     676   1064        364

In [7]:
df.head(2)

age     sex    bmi  children smoker     region     charges
0   19  female  27.90         0    yes  southwest  16884.9240
1   18    male  33.77         1     no  southeast   1725.5523

In [8]:
df.region.unique()

array(['southwest', 'southeast', 'northwest', 'northeast'], dtype=object)

In [9]:
df.children.unique()

array([0, 1, 3, 2, 5, 4], dtype=int64)

In [10]:
X = df.iloc[:,:-1].values
Y = df.iloc[:,-1].values

In [11]:
#spliting the data into train test split
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(X,Y,random_state=42,test_size=0.2)

In [12]:
xtrain.shape,xtest.shape

((1070, 6), (268, 6))

In [13]:
xtrain[0]

array([46, 'female', 19.95, 2, 'no', 'northwest'], dtype=object)

In [14]:
#performing one hot encoding and standardization
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1,4,5])],remainder='passthrough')
xtrain = ct.fit_transform(xtrain)

In [15]:
xtrain[0]

array([1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 46, 19.95, 2], dtype=object)

In [16]:
xtest = ct.transform(xtest)

In [17]:
xtest[0]

array([1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 45, 25.175, 2],
      dtype=object)

In [18]:
# feature scaling 
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
xtrain[:,[8,9,10]] = sc.fit_transform(xtrain[:,[8,9,10]])

In [19]:
xtrain[0]

array([1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.4722265067674694,
       -1.7565251299004097, 0.734336259529673], dtype=object)

In [20]:
xtest[:,[8,9,10]] =  sc.transform(xtest[:,[8,9,10]])

In [21]:
xtest[0]

array([1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.401140074263081,
       -0.891539245398062, 0.734336259529673], dtype=object)

In [22]:
from sklearn.ensemble import RandomForestRegressor
rfr = RandomForestRegressor(n_estimators=10)
rfr.fit(xtrain,ytrain)
predict = rfr.predict(xtest)

In [23]:
pd.DataFrame(data={'ytest':ytest,'predict':predict})

ytest       predict
0     9095.06825   8838.176825
1     5272.17580   4648.516375
2    29330.98315  28457.095475
3     9301.89355  14686.805401
4    33750.29180  35093.294787
..           ...           ...
263  47055.53210  46703.580160
264  12222.89830  11753.478045
265   6067.12675   6465.992620
266  63770.42801  47843.156135
267   9872.70100   9954.943360

[268 rows x 2 columns]

In [24]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(ytest,predict)
np.sqrt(mse)

4823.677420819416